# Generated by Django 5.2.8 on 2025-11-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.PositiveIntegerField(blank=True, null=True)),
                ('admission_name', models.CharField(max_length=255, verbose_name='Name of Student')),
                ('date_of_joining', models.DateField(blank=True, null=True, verbose_name='Date of Joining')),
                ('class_roll_no', models.CharField(blank=True, max_length=50, verbose_name='Class Roll-No')),
                ('exam_roll_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Exam Roll No')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile No')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('aadhaar', models.CharField(blank=True, max_length=30, verbose_name='Aadhaar No')),
                ('present_address', models.TextField(blank=True, verbose_name='Present Address')),
                ('permanent_address', models.TextField(blank=True, verbose_name='Permanent Address')),
                ('inter_stream', models.CharField(blank=True, max_length=150, verbose_name='+2 Stream')),
                ('inter_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='+2 % / CGPA')),
                ('inter_regd_no', models.CharField(blank=True, max_length=80, verbose_name='+2 Regd No')),
                ('inter_college', models.CharField(blank=True, max_length=255, verbose_name='+2 College Name')),
                ('grad_stream', models.CharField(blank=True, max_length=150, verbose_name='Graduation Stream')),
                ('grad_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Graduation % / CGPA')),
                ('grad_regd_no', models.CharField(blank=True, max_length=80, verbose_name='Graduation Regd No')),
                ('grad_college', models.CharField(blank=True, max_length=255, verbose_name='Graduation College Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['class_roll_no', 'admission_name'],
            },
        ),
    ]
