# Generated by Django 5.2.8 on 2025-12-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_user_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['department', 'class_roll_no', 'admission_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='board_10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='10th Board / University'),
        ),
        migrations.AddField(
            model_name='student',
            name='board_12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='12th Board / University'),
        ),
        migrations.AddField(
            model_name='student',
            name='clc_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CLC No'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('MPMIR', 'MPMIR'), ('OTHER', 'OTHER')], default='BCA', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Father's Name"),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Mother's Name"),
        ),
        migrations.AddField(
            model_name='student',
            name='percentage_10',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='10th % / CGPA'),
        ),
        migrations.AddField(
            model_name='student',
            name='percentage_12',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='12th % / CGPA'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact No 2'),
        ),
        migrations.AddField(
            model_name='student',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='regd_no_12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='12th Regd No'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_10',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='10th School Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_12',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='12th School/College Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='year_10',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='10th Year'),
        ),
        migrations.AddField(
            model_name='student',
            name='year_12',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='12th Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grad_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Graduation % / CGPA'),
        ),
        migrations.AlterField(
            model_name='student',
            name='inter_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='+2 % / CGPA'),
        ),
    ]
