# Generated by Django 5.2.8 on 2025-12-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_options_student_board_10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_roll_no', 'admission_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='board_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='board_12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='clc_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='percentage_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='percentage_12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_secondary',
        ),
        migrations.RemoveField(
            model_name='student',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='student',
            name='regd_no_12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_12',
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('MPMIR', 'MPMIR')], default='BCA', max_length=20, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grad_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Graduation % / CGPA'),
        ),
        migrations.AlterField(
            model_name='student',
            name='inter_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='+2 % / CGPA'),
        ),
    ]
